[Service]
# Disable seccomp filtering
MemoryDenyWriteExecute=no
NoNewPrivileges=no
PrivateDevices=no
ProtectKernelTunables=no
ProtectKernelModules=no
ProtectControlGroups=no
RestrictRealtime=no
SystemCallFilter=
SystemCallArchitectures=
