---

- name: Configure pi-hole
  become: true
  become_method: ansible.builtin.sudo
  notify: restart pihole-FTL
  block:
    - name: Copy pihole-FTL service override configuration files
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ systemd_unit_dir }}/pihole-FTL.service.d/{{ item | basename }}"
        mode: "0644"
      with_fileglob:
        - "files/pihole-FTL.service.d/*.conf"

    - name: Copy pihole teleporter file
      ansible.builtin.copy:
        src: "files/{{ pihole_teleporter_filename }}"
        dest: "{{ pihole_teleporter_dest }}/{{ pihole_teleporter_filename }}"
        mode: "0644"

    - name: Import pihole teleporter file
      ansible.builtin.command:
        cmd: "pihole-FTL --teleporter {{ pihole_teleporter_dest }}/{{ pihole_teleporter_filename }}"
      register: pihole_import
      changed_when: pihole_import.rc != 0 # <- Uses the return code to define when the task has changed.

    - name: Remove pihole teleporter file
      ansible.builtin.file:
        path: "{{ pihole_teleporter_dest }}/{{ pihole_teleporter_filename }}"
        state: absent
