---
- name: Configure NTPD
  hosts: raspberrypi
  gather_facts: false

  handlers:
    - name: Import global handlers
      ansible.builtin.import_tasks: roles/common/handlers/main.yml

  roles:
    - role: configure_ntpd
#    - role: configure_ufw
