---
- name: Install unbound server
  hosts: raspberrypi
  gather_facts: false

  handlers:
    - name: Import global handlers
      ansible.builtin.import_tasks: roles/common/handlers/main.yml

  roles:
    - role: install_unbound
    - role: configure_unbound
