---

- hosts: localhost
  gather_facts: no
  tasks:

    - name: Rebuild ~/aws directory
      file: 
        path: ~/aws
        state: "{{ item }}"
      with_items:
        - absent
        - directory

    - name: Rebuild ~/repos directory
      file: 
        path: ~/repos
        state: "{{ item }}"
      with_items:
        - absent
        - directory

    - name: Rebuild ~/tools directory
      file: 
        path: ~/tools
        state: "{{ item }}"
      with_items:
        - absent
        - directory

- hosts: rpi
  gather_facts: yes
  tasks:

    - name: Register remote backup_files 
      shell: "ls -1 ~/ansible_backup/*_*.tar.gz"
      register: backup_files

    - name: Download backup files
      fetch:
        src: "{{ item }}"
        dest: "/tmp/{{ item | basename }}"
        flat: yes
      with_items: "{{ backup_files.stdout_lines }}"

- hosts: localhost
  gather_facts: no
  tasks: 
    - name: Register aws backup file
      shell: "ls -1 /tmp/aws_*.tar.gz"
      register: aws_backup
    
    - name: Register repos backup file
      shell: "ls -1 /tmp/repos_*.tar.gz"
      register: repos_backup

    - name: Register tools backup file
      shell: "ls -1 /tmp/tools_*.tar.gz"
      register: tools_backup

    - name: Extract aws backup
      unarchive:
        src: "{{ aws_backup.stdout }}"
        dest: "~/aws"

    - name: Extract repos backup
      unarchive:
        src: "{{ repos_backup.stdout }}"
        dest: "~/repos"

    - name: Extract tools backup
      unarchive:
        src: "{{ tools_backup.stdout }}"
        dest: "~/tools"
    
    - name: Source backup files cleanup
      file: 
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ aws_backup.stdout }}"
        - "{{ repos_backup.stdout }}"
        - "{{ tools_backup.stdout }}"

...
