---
- name: Start all DNS services
  hosts: pihole
  gather_facts: false

  vars:
    service_state: started
    service_action: starting

  roles:
    - role: common
      vars:
        service_name: unbound

    - role: common
      vars:
        service_name: pihole-FTL
