---

## Cron config
configure_cron_jobs:

  - name: "Update Gravity"
    minute: "00"
    hour: "04"
    command: "{{ pihole_bin_dir }}/pihole -g"

  - name: "Optimize FTL Database"
    hour: "03"
    minute: "00"
    weekday: "1"
    command: "/root/.local/bin/optimize_FTL.sh"

  - name: "Update Pi-hole"
    minute: "00"
    hour: "02"
    command: "{{ pihole_bin_dir }}/pihole -up > /var/log/pihole/piholeUpdate.log 2>&1"

configure_cron_scripts_root: "/root/.local/bin"
