---

## Cron config
configure_cron_jobs:
  - name: "Sync FileSystem"
    minute: "0/5"
    command: "/usr/bin/sync"

  - name: "Update Gravity"
    minute: "00"
    hour: "04"
    command: "/usr/local/bin/pihole -g"

  - name: "Optimize FTL Database"
    hour: "03"
    minute: "00"
    day_of_week: "1"
    command: "/root/.local/bin/optimize_FTL.sh"

  - name: "Update Pi-hole"
    minute: "00"
    hour: "02"
    command: "/usr/local/bin/pihole -up > /var/log/pihole/piholeUpdate.log 2>&1"

  - name: "Cleanup tmp"
    minute: "00"
    hour: "01"
    day: "*/7"
    command: "/usr/bin/find /tmp -type f -mtime +7 -delete"

  - name: "Cleanup logs"
    minute: "00"
    hour: "00"
    day: "*/7"
    command: "/usr/bin/find /var/log -type f -mtime +7 -delete"

configure_cron_scripts_root: "/root/.local/bin"
