---

## Cron config
configure_cron_jobs:
  # - name: "This unbound restart avoid bogus resolver status after reboot"
  #   minute: "@reboot"
  #   command: "sleep 120 && systemctl restart unbound"

  - name: "Sync FileSystem"
    minute: "*/10"
    command: "/usr/bin/sync"

  - name: "Update Gravity"
    minute: "00"
    hour: "04"
    command: "{{ pihole_bin_dir }}/pihole -g"

  - name: "Optimize FTL Database"
    hour: "03"
    minute: "00"
    weekday: "1"
    command: "/root/.local/bin/optimize_FTL.sh"

  - name: "Update Pi-hole"
    minute: "00"
    hour: "02"
    command: "{{ pihole_bin_dir }}/pihole -up > /var/log/pihole/piholeUpdate.log 2>&1"

  - name: "Cleanup tmp"
    minute: "00"
    hour: "01"
    weekday: "0"
    command: "/usr/bin/find /tmp -type f -mtime +7 -delete"

  - name: "Cleanup logs"
    minute: "00"
    hour: "00"
    weekday: "0"
    command: "/usr/bin/find /var/log/ -type f -mtime +7 -delete"

configure_cron_scripts_root: "/root/.local/bin"
