[raspberrypi]
rpi ansible_host=192.168.10.2 

[raspberrypi:vars]

## pi-hole configuration variables


## Unbound configuration variables
unbound_config_dir="/etc/unbound"
unbound_daemon_config_dir="{{ unbound_config_dir }}/unbound.conf.d"
unbound_user="unbound"
unbound_group="unbound"
unbound_root_hints_dir="/usr/share/dns"

## Valkey configuration variables
valkey_port=0
valkey_config_dir="/etc/valkey"
valkey_user="valkey"
valkey_group="valkey"
valkey_max_memory="32mb"
valkey_unixsocket="/run/valkey/valkey.sock"
valkey_dbfilename="dump.rdb"
valkey_db_dir="/var/lib/valkey"

## Systemd variables
systemd_unit_dir="/etc/systemd/system"
