[raspberrypi]
rpi ansible_host=192.168.10.2 

[raspberrypi:vars]

## LAN related variables
lan_network="192.168.10.0/24"

## pi-hole configuration variables
pihole_teleporter_filename="pihole_teleporter.zip"
pihole_teleporter_vault="roles/configure_pihole/files"
pihole_teleporter_dest="/tmp"

## Unbound configuration variables
unbound_config_dir="/etc/unbound"
unbound_daemon_config_dir="{{ unbound_config_dir }}/unbound.conf.d"
unbound_user="unbound"
unbound_group="unbound"
unbound_root_hints_dir="/usr/share/dns"

## Valkey configuration variables
valkey_port=0
valkey_config_dir="/etc/valkey"
valkey_user="valkey"
valkey_group="valkey"
valkey_max_memory="32mb"
valkey_unixsocket="/run/valkey/valkey.sock"
valkey_dbfilename="dump.rdb"
valkey_db_dir="/var/lib/valkey"

## Systemd variables
systemd_unit_dir="/etc/systemd/system"
