[all:vars]
ansible_managed="ANSIBLE MANAGED: file updated by {{ ansible_user_id | default('ansible') }}, any manual changes on this file will be overwritten."

[pihole]
orangepi ansible_host=192.168.10.3 host_interface=end0

[pihole:vars]
## LAN related variables
lan_network="192.168.10.0/24"

## NTP package name
ntp_package="chrony"    # It can be chrony or ntp depending on the system and preference
ntp_pool="south-america.pool.ntp.org"

## pi-hole configuration variables
pihole_root_dir="/etc/pihole"
pihole_teleporter_filename="pihole_teleporter.zip"
pihole_teleporter_vault="roles/configure_pihole/files"
pihole_teleporter_dest="/tmp"
pihole_default_webpassword="admin"
pihole_bin_dir="/usr/local/bin"
pihole_logrotate_config_dir="/etc/logrotate.d"
pihole_logrotate_config_file="pihole"
pihole_logrotate_days=2

## Unbound configuration variables
unbound_config_dir="/etc/unbound"
unbound_daemon_config_dir="{{ unbound_config_dir }}/unbound.conf.d"
unbound_user="unbound"
unbound_group="unbound"
unbound_root_hints_dir="/usr/share/dns"

## Systemd variables
systemd_unit_dir="/etc/systemd/system"

## /tmp maintenance configuration variables
tmp_retention_days=7
systemd_tmpfiles_config_dir="/etc/tmpfiles.d"
systemd_tmpfiles_config_file="tmp.conf"

## /var/tmp maintenance configuration variables
var_tmp_retention_days=7

## journalctl retention configuration variables for low resources arm based devices
## this is the configuration for jinja2 template 00-arm-optimized.conf.j2
journalctl_config_dir="/etc/systemd/journald.conf.d"
journalctl_config_file="00-arm-optimized.conf"
journalctl_storage="volatile"
journalctl_max_use="32M"
journalctl_max_file_size="8M"
journalctl_compress="no"
journalctl_rate_limit_interval="30s"
journalctl_rate_limit_burst=200
journalctl_audit="no"
journalctl_ForwardToWall="no"
journalctl_ForwardToSyslog="no"
