---
- name: Configure NTPD
  become: true
  become_method: ansible.builtin.sudo
  block:
    - name: Ensure NTPD is installed
      ansible.builtin.package:
        name: ntp
        state: present

    - name: Configure NTPD
      ansible.builtin.copy:
        src: files/ntp.conf
        dest: /etc/ntp.conf
        owner: root
        group: root
        mode: '0644'
      notify: Restart ntpd
