---
- name: "Configure {{ ntp_package }} as NTPD"
  when: ntp_package == "ntp"
  become: true
  become_method: ansible.builtin.sudo
  block:
    - name: Ensure {{ ntp_package }} is installed
      ansible.builtin.package:
        name: ntp
        state: present

    - name: Configure {{ ntp_package }}
      ansible.builtin.template:
        src: templates/ntp.conf.j2
        dest: /etc/ntp.conf
        owner: root
        group: root
        mode: '0644'
      notify: Restart {{ ntp_package }}

- name: "Configure {{ ntp_package }} (chrony) as NTPD"
  when: ntp_package == "chrony"
  become: true
  become_method: ansible.builtin.sudo
  block:
    - name: Ensure {{ ntp_package }} is installed
      ansible.builtin.package:
        name: "{{ ntp_package }}"
        state: present

    - name: Configure {{ ntp_package }}
      ansible.builtin.template:
        src: "templates/{{ ntp_package }}.conf.j2"
        dest: "/etc/{{ ntp_package }}/{{ ntp_package }}.conf"
        owner: root
        group: root
        mode: '0644'
      notify: Restart {{ ntp_package }}
