---

- name: Configure unbound
  become: true
  become_method: ansible.builtin.sudo
  notify:
    - Restart unbound
    - Restart pihole-FTL
  block:
    - name: Upload unbound.conf file
      ansible.builtin.template:
        src: unbound.conf.j2
        dest: "{{ unbound_config_dir }}/unbound.conf"
        owner: "{{ unbound_user }}"
        group: "{{ unbound_group }}"
        mode: "0644"

    - name: Download root.hints file
      ansible.builtin.get_url:
        url: https://www.internic.net/domain/named.cache
        dest: "{{ unbound_config_dir }}/root.hints"
        owner: "{{ unbound_user }}"
        group: "{{ unbound_group }}"
        mode: '0644'

    - name: Rebuild configuration directory unbound.conf.d
      ansible.builtin.file:
        path: "{{ unbound_config_dir }}/unbound.conf.d"
        state: "{{ item }}"
        owner: "{{ unbound_user }}"
        group: "{{ unbound_group }}"
        mode: "0644"
      loop:
        - absent
        - directory

    - name: Upload unbound.conf.d configuration files
      ansible.builtin.template:
        src: "{{ item }}"
        dest: "{{ unbound_config_dir }}/unbound.conf.d/{{ item | basename | regex_replace('\\.j2$', '') }}"
        owner: "{{ unbound_user }}"
        group: "{{ unbound_group }}"
        mode: "0644"
      with_fileglob:
        - "templates/unbound.conf.d/*.conf.j2"

    - name: Check unbound configuration
      ansible.builtin.command: unbound-checkconf
      register: unbound_checkconf
      failed_when: unbound_checkconf.rc != 0
      changed_when: false

    - name: Unbound control setup
      ansible.builtin.command: unbound-control-setup
      register: unbound_control_setup
      failed_when: unbound_control_setup.rc != 0
      changed_when: false
