---
- name: Import pihole teleporter configuration
  become: true
  become_method: ansible.builtin.sudo
  block:
    - name: Generate pihole teleporter file
      ansible.builtin.command:
        cmd: pihole-FTL --teleporter
      args:
        chdir: "{{ pihole_teleporter_dest }}"
      register: pihole_export
      changed_when: pihole_export.rc != 0

    - name: Pihole teleporter file generated
      ansible.builtin.debug:
        var: pihole_export

    - name: Fetch pihole teleporter file
      ansible.builtin.fetch:
        src: "{{ pihole_teleporter_dest }}/{{ pihole_export.stdout }}"
        dest: "{{ pihole_teleporter_vault }}/{{ pihole_teleporter_filename }}"
        flat: true
      register: pihole_fetch

    - name: Remove pihole teleporter file
      ansible.builtin.file:
        path: "{{ pihole_teleporter_dest }}/{{ pihole_export.stdout }}"
        state: absent
