---
## DO NOT Change the handlers order because it will impact the order services get restarted

- name: Restart unbound
  ansible.builtin.include_tasks: ../tasks/manage_service.yml
  vars:
    service_name: unbound
    service_state: restarted
    service_action: restart
    service_daemon_reload: true

- name: Restart pihole-FTL
  ansible.builtin.include_tasks: ../tasks/manage_service.yml
  vars:
    service_name: pihole-FTL
    service_state: restarted
    service_action: restart
    service_daemon_reload: true

- name: "Restart {{ ntp_package }}"
  ansible.builtin.include_tasks: ../tasks/manage_service.yml
  vars:
    service_name: "{{ ntp_package }}"
    service_state: restarted
    service_action: restart
    service_daemon_reload: true
