---

- name: Configure Valkey Cache
  become: true
  become_method: ansible.builtin.sudo
  block:
  - name: Configure Valkey
    ansible.builtin.template:
      src: valkey.conf.j2
      dest: "{{ valkey_config_dir }}/valkey.conf"
      owner: "{{ valkey_user }}"
      group: "{{ valkey_group }}"
      mode: "0644"

  - name: Upload valkey systemd configuration files
    ansible.builtin.copy:
      src: "{{ item }}"
      dest: "{{systemd_unit_dir}}/valkey-server.service.d/{{ item | basename }}"
      owner: root
      group: root
      mode: "0644"
    with_fileglob:
      - "files/valkey-server.service.d/*.conf"
  notify: Restart valkey
