---
# This file handles service management
- name: "Perform {{ action_type }} operation on DNS stack"
  ansible.builtin.service:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  loop: "{{ stack_order }}"
