---
- name: Populate service facts
  ansible.builtin.service_facts:

- name: Reload systemd daemon
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
  when: 
    - service_daemon_reload | default(false)
    - (service_name + '.service') in ansible_facts.services

- name: "{{ service_state | capitalize }} service {{ service_name }}"
  become: true
  ansible.builtin.systemd:
    name: "{{ service_name }}"
    state: "{{ service_state }}"
    enabled: "{{ service_enabled | default(true) }}"
  when:
    - service_name is defined
    - service_state is defined
    - (service_name + '.service') in ansible_facts.services
