name: Deploy configure-unbound Ansible Playbook
on:
  push:
    branches:
      - main
    paths:
      - 'roles/configure_unbound/templates/**'

jobs:
  run-configure-unbound:
    runs-on: self-hosted
    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Ansible Playbook
        run: |
          ansible-playbook configure_unbound.yml

      - name: Cleanup workspace
        if: always()
        run: |
          echo "Cleanup workspace..."
          rm -rf "${{ github.workspace }}"/*
          rm -rf "${{ github.workspace }}"/.[!.]*